---
- name: Ensure Docker is logged into Docker Hub
  hosts: dockerexcludesynology,rpidockerswarm
  become: yes
  gather_facts: no

  vars:
    dockerhub_registry: "docker.io"  # Use "docker.io" here to match the key in JSON output
    dockerhub_username: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}"
    dockerhub_password: "{{ lookup('env', 'DOCKERHUB_PASSWORD') }}"

  tasks:
    - name: Check if Docker is already logged in to Docker Hub
      command: >
        docker info --format '{{"{{json .RegistryConfig.IndexConfigs}}"}}'
      register: docker_info
      changed_when: false
      failed_when: false

    - name: Show raw Docker info output (for debugging)
      shell: docker info --format '{{json .RegistryConfig.IndexConfigs}}'
      register: docker_info
      changed_when: false

    - name: Determine if login is needed
      set_fact:
        docker_login_needed: >-
          {{
            docker_info.rc != 0 or
            (
              docker_info.stdout is defined and
              docker_info.stdout | length > 0 and
              (
                (docker_info.stdout | from_json).get(dockerhub_registry, {}).get('auth') is not defined
              )
            )
          }}

    - name: Debug docker_login_needed fact
      debug:
        msg: "Docker login needed: {{ docker_login_needed }}"

    - name: Fail if DockerHub credentials are missing
      fail:
        msg: "DockerHub credentials (username/password) are not set in environment variables."
      when: docker_login_needed and (dockerhub_username == '' or dockerhub_password == '')

    - name: Login to Docker Hub if not already authenticated
      community.docker.docker_login:
        registry_url: "https://index.docker.io/v1/"
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
      when: docker_login_needed

    - name: Confirm Docker is authenticated to Docker Hub
      command: >
        docker info --format '{{"{{json .RegistryConfig.IndexConfigs}}"}}'
      register: docker_info_check
      changed_when: false
      failed_when: false

    - name: Show raw Docker info output after login attempt (for debugging)
      debug:
        msg: "{{ docker_info_check.stdout }}"

    - name: Set Docker Hub auth presence fact (safely)
      set_fact:
        docker_hub_authenticated: >-
          {{
            (
              docker_info_check.stdout is defined and
              docker_info_check.stdout | length > 0 and
              (
                (docker_info_check.stdout | from_json).get(dockerhub_registry, {}).get('auth') is defined
              )
            )
          }}

    - name: Show Docker Hub auth status
      debug:
        msg: "Docker Hub auth present: {{ docker_hub_authenticated }}"
