---
- name: Ensure Docker is logged into Docker Hub with expiry reminder
  hosts: dockerexcludesynology,rpidockerswarm
  become: yes
  gather_facts: no

  vars:
    dockerhub_registry: "https://index.docker.io/v1/"
    dockerhub_username: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}"
    dockerhub_password: "{{ lookup('env', 'DOCKERHUB_PASSWORD') }}"

  tasks:

    - name: Check if Docker is already logged in to Docker Hub
      command: docker info --format '{{json .RegistryConfig.IndexConfigs}}'
      register: docker_info
      changed_when: false
      failed_when: false

    - name: Determine if login is needed
      set_fact:
        docker_login_needed: >-
          {{
            (docker_info.rc != 0) or
            ('auth' not in (docker_info.stdout | from_json).get(dockerhub_registry, {}))
          }}

    - name: Login to Docker Hub if not already authenticated
      community.docker.docker_login:
        registry_url: "{{ dockerhub_registry }}"
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
      when: docker_login_needed
