---
- name: Update Proxmox Linux VM
  hosts: proxmox-linux-vms
  ignore_unreachable: yes
  gather_facts: yes
  become: yes

  tasks:

#  - name: Check Proxmox Agent is present / installed
  - name: Install qemu guest agent
    ansible.builtin.apt:
     name: qemu-guest-agent
     state: present
    #when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'Ubuntu'


