---

- name: Prune docker servers
  gather_facts: true
  hosts: docker, rpidockerswarm
  become: yes
  tasks:

  #- name: Manual docker command to prune
  #  ansible.builtin.shell: docker image prune -af
  - name: Prune via docker module
    community.docker.docker_prune:
     containers: false
     images: true
     networks: false
     volumes: false
     builder_cache: false
     timeout: 120

