---
- name: Baseline setup for Raspberry Pi Docker Swarm nodes
  hosts: rpidockerswarm
  become: true

  vars:
    nfs_server: "192.168.0.4"
    nfs_share: "/volume1/docker"
    mount_point: "/mnt/ds918-docker"

  tasks:

    - name: Ensure APT cache is updated
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
        autoremove: yes

    - name: Disable Wi-Fi (dtoverlay method for all Pi models)
      lineinfile:
        path: /boot/config.txt
        line: "dtoverlay=disable-wifi"
        state: present
      notify: reboot_required

    - name: Disable wireless interface at runtime
      command: nmcli radio wifi off
      when: ansible_facts['distribution'] == 'Raspbian' or ansible_facts['distribution'] == 'Debian'

    - name: Install NFS client packages
      apt:
        name: nfs-common
        state: present

    - name: Create the NFS mount directory
      file:
        path: "{{ mount_point }}"
        state: directory
        mode: '0755'

    - name: Mount NFS share
      mount:
        src: "{{ nfs_server }}:{{ nfs_share }}"
        path: "{{ mount_point }}"
        fstype: nfs
        opts: rw,vers=4
        state: mounted

    - name: Ensure NFS mount is persistent on boot
      mount:
        src: "{{ nfs_server }}:{{ nfs_share }}"
        path: "{{ mount_point }}"
        fstype: nfs
        opts: rw,vers=4
        state: present

    - name: Install Docker dependencies (optional, prep for Docker install)
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

  handlers:
    - name: reboot_required
      reboot:
        msg: "Rebooting to apply changes (e.g., Wi-Fi disabled)"
        connect_timeout: 5
        reboot_timeout: 600
