---
- hosts: sshkeytest
  vars:
   - semaphore_password: 'ansibleadmin1'
  gather_facts: no
  #remote_user: root
 
  tasks:

  - name: Add a new user named semaphore
    user:
         name=semaphoretest
         password={{ semaphore_password }}

  - name: Add semaphoretest user to the sudoers
    copy:
         dest: "/etc/sudoers.d/semaphoretest"
         content: "semaphoretest  ALL=(ALL)  NOPASSWD: ALL"

  #- name: Deploy SSH Key
  #  authorized_key: user=semaphoretest
  #                  key="{{ lookup('file', '/home/semaphore/.ssh/id_rsa.pub') }}"
  #                  state=present

 # - name: Disable Password Authentication
 #   lineinfile:
 #         dest=/etc/ssh/sshd_config
 #         regexp='^PasswordAuthentication'
 #         line="PasswordAuthentication no"
 #         state=present
 #         backup=yes
 #   notify:
 #     - restart ssh

#  - name: Disable Root Login
#    lineinfile:
#          dest=/etc/ssh/sshd_config
#          regexp='^PermitRootLogin'
#          line="PermitRootLogin no"
#          state=present
#          backup=yes
#    notify:
#      - restart ssh

  handlers:
  - name: restart ssh
    service:
      name=sshd
      state=restarted
