---
- hosts: sshkeytest
  vars:
   - semaphore_password: '$5$k7QFr1iCgzt0pLbW$kORL7zDfq6p06DQKEJnM10GiI2E1x39FPYzYfMxxwd4'
  gather_facts: no
  remote_user: root
 
  tasks:

  - name: Add a new user named semaphore
    user:
         name=semaphore
         password={{ semaphore_password }}

  - name: Add semaphore user to the sudoers
    copy:
         dest: "/etc/sudoers.d/semaphore"
         content: "semaphore  ALL=(ALL)  NOPASSWD: ALL"

  - name: Deploy SSH Key
    authorized_key: user=semaphore
                    key="{{ lookup('file', '/home/semaphore/.ssh/id_rsa.pub') }}"
                    state=present

  - name: Disable Password Authentication
    lineinfile:
          dest=/etc/ssh/sshd_config
          regexp='^PasswordAuthentication'
          line="PasswordAuthentication no"
          state=present
          backup=yes
    notify:
      - restart ssh

  - name: Disable Root Login
    lineinfile:
          dest=/etc/ssh/sshd_config
          regexp='^PermitRootLogin'
          line="PermitRootLogin no"
          state=present
          backup=yes
    notify:
      - restart ssh

  handlers:
  - name: restart ssh
    service:
      name=sshd
      state=restarted
