---
- hosts: sshkeytest
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - debug: msg="Ansible running in {{ansible_lsb.id}}!"
    - name: Update Apt
      apt: update_cache=yes
      when: ansible_facts['os_family'] == 'Debian'
      register: apt_updated
